name: Bug Report
description: File a bug report
labels: ["bug"]
body:
    - type: textarea
      id: what-happened
      attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is.
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: To Reproduce
          description: Steps to reproduce the behavior.
      validations:
          required: true
    - type: input
      id: plugin-version
      attributes:
          label: Avalonia for VS Code
          placeholder: e.g. v0.10.18
      validations:
          required: true
    - type: input
      id: avalonia-version
      attributes:
          label: Avalonia version
          placeholder: e.g. 0.10.18, 11.0
    - type: input
      id: vs-version
      attributes:
          label: VS Code version
          placeholder: e.g. v0.0.25
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output
          description: Please attach any relevant log output. You can find the logs in the Output panel (View -> Output) under the Avalonia for VS Code channel.
          render: shell
      validations:
          required: true
    - type: textarea
      id: additional-info
      attributes:
          label: Additional context
          description: |
              Add any other context about the problem here.
              If applicable, add screenshots to help explain your problem.
