blank_issues_enabled: false
contact_links:
  - name: Report issues in Avalonia Pro repository
    url: https://github.com/AvaloniaUI/AvaloniaPro/issues/new/choose
    about: Please file bugs and feature requests in the Avalonia Pro repository.
